#!/usr/bin/env sh
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  202207042123-git
# @Author            :  Jason Hempstead
# @Contact           :  jason@casjaysdev.com
# @License           :  LICENSE.md
# @ReadME            :  tmux_weather --help
# @Copyright         :  Copyright: (c) 2022 Jason Hempstead, Casjays Developments
# @Created           :  Saturday, Jul 09, 2022 15:32 EDT
# @File              :  tmux_weather
# @Description       :
# @TODO              :
# @Other             :
# @Resource          :
# @sudo/root         :  no
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME="$(basename "$0" 2>/dev/null)"
VERSION="202207042123-git"
HOME="${USER_HOME:-$HOME}"
USER="${SUDO_USER:-$USER}"
RUN_USER="${SUDO_USER:-$USER}"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set bash options
if [ "$1" = "--debug" ]; then shift 1 && set -xo && export SCRIPT_OPTS="--debug" && export _DEBUG="on"; fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Check for needed applications
#type -P sh &>/dev/null || exit 1 # exit if not found
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set variables

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set functions
__version() { echo "$VERSION"; }

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set additional variables
exitCode="0"
TMUX_WEATHER_CONFIG_DIR="$HOME/.config/$APPNAME"
TMUX_WEATHER_CONFIG_FILE="settings.conf"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# bring in user config
[ -f "$TMUX_WEATHER_CONFIG_DIR/$TMUX_WEATHER_CONFIG_FILE" ] && . "$TMUX_WEATHER_CONFIG_DIR/$TMUX_WEATHER_CONFIG_FILE"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Argument/Option settings
SETARGS="$*"
SHORTOPTS="v,h"
LONGOPTS="config,version,help"
ARRAY=""
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Setup application options
setopts=$(getopt -o "$SHORTOPTS" --long "$LONGOPTS" -n "$APPNAME" -- "$@" 2>/dev/null)
eval set -- "${setopts}" 2>/dev/null
while :; do
  case "$1" in
  --version)
    shift 1
    __version
    ;;
  --help)
    shift 1
    printf 'help'
    exit
    ;;
  --config)
    shift 1
    echo "" >"$TMUX_WEATHER_CONFIG_DIR/$TMUX_WEATHER_CONFIG_FILE"
    ;;
  --)
    shift 1
    break
    ;;
  esac
done
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Main application
if [ -f "$HOME/.cache/tmux_weather" ]; then
  find "$HOME/.cache" -maxdepth 1 -mmin +300 -type f -name tmux_weather | grep '^' &&
    rm -Rf "$HOME/.cache/tmux_weather"
  exitCode=1
fi
if [ ! -s "$HOME/.cache/tmux_weather" ] && [ "$exitCode" -ne 0 ]; then
  curl -q -ILSsf -m 1 --retry 1 "https://1.1.1.1" | grep -qi 'server:*.cloudflare' &&
    curl -q -LSsf -m 1 "https://wttr.in/?format=3" 2>/dev/null | awk '{print $1,$(NF-1),$NF}' | sed 's|, |: |g' | grep '^' >"$HOME/.cache/tmux_weather" || echo ''
fi
if [ -f "$HOME/.cache/tmux_weather" ]; then
  grep -s '^' "$HOME/.cache/tmux_weather"
  exitCode="$?"
fi
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# End application
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# lets exit with code
exit ${exitCode:-$?}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end
